# S3 connector configuration for LocalStack
#
# Prerequisites:
#   make localstack-start
#   make localstack-setup
#
# Usage:
#   make run-s3-localstack

logging:
  level: debug

connectors:
  s3:
    bucket: test-bucket
    region: us-east-1
    endpoint: "http://localhost:4566"
    force_path_style: true
    cache:
      type: filesystem
      path: /tmp/fuse-adapter/cache/s3
      max_size: "512MB"
      flush_interval: 30s

mounts:
  - path: /tmp/fuse-adapter/s3-mount1
    connector:
      type: s3
      prefix: "data/exports"
  - path: /tmp/fuse-adapter/s3-mount2
    connector:
      type: s3
      prefix: "data/imports"
